dist: trusty
os: linux
language: minimal

git:
  depth: 1

env:
  global:
    - MAKEJOBS=-j3

addons:
  apt:
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
before_install:
  - export MAKEFLAGS="-j3"
install: true
script:
  - ./configure --prefix=/tmp/build-default --disable-multilib
  - (make > /dev/null) || (make -j1 && exit 1)
